/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-16 07:40:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Editorial by HTML5 UP\r\n");
      out.write("	html5up.net | @ajlkn\r\n");
      out.write("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>Generic - Editorial by HTML5 UP</title>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"assets/css/main.css\"/>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"assets/css_board/css.css\">\r\n");
      out.write("	</head>\r\n");
      out.write("	<style>\r\n");
      out.write("		.pagination{\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		.board_wrap {\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		.count{\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("	<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Wrapper -->\r\n");
      out.write("			<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Main -->\r\n");
      out.write("					<div id=\"main\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Header -->\r\n");
      out.write("								<header id=\"header\">\r\n");
      out.write("									<a href=\"safeboxcheck.html\" class=\"logo\" style=\"font-size: 20px;\"><strong>관리 일지 목록</strong></a>\r\n");
      out.write("									<ul class=\"icons\">\r\n");
      out.write("										<li><a href=\"fieldlist.html\" class=\"logo\"><span class=\"label\"><strong>현장목록</strong></span></a></li>\r\n");
      out.write("                              			\r\n");
      out.write("                                        <li><a href=\"notice.html\" class=\"logo\"><span class=\"label\">경고발생현황</span></a></li>  										\r\n");
      out.write("									</ul>\r\n");
      out.write("								</header>\r\n");
      out.write("\r\n");
      out.write("							<!-- Content -->\r\n");
      out.write("								<section>\r\n");
      out.write("									<div class=\"board_wrap\">\r\n");
      out.write("										<div class=\"board_title\">\r\n");
      out.write("										\r\n");
      out.write("											<!-- <p>공지사항을 빠르고 정확하게 안내해드립니다.</p> -->\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"board_list_wrap\">\r\n");
      out.write("											<div class=\"board_list\">\r\n");
      out.write("												<div class=\"top\">\r\n");
      out.write("													<div class=\"num\">번호</div>\r\n");
      out.write("													<div class=\"title\">제목</div>\r\n");
      out.write("													<div class=\"writer\">글쓴이</div>\r\n");
      out.write("													<div class=\"date\">작성일</div>\r\n");
      out.write("													<div class=\"count\"></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"num\">5</div>\r\n");
      out.write("													<div class=\"title\"><a href=\"view.html\">글 제목이 들어갑니다.</a></div>\r\n");
      out.write("													<div class=\"writer\">김이름</div>\r\n");
      out.write("													<div class=\"date\">2021.1.15</div>\r\n");
      out.write("													<div class=\"count\"><a href=\"board_edit.html\" class=\"button\">수정</a></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"num\">4</div>\r\n");
      out.write("													<div class=\"title\"><a href=\"view.html\">글 제목이 들어갑니다.</a></div>\r\n");
      out.write("													<div class=\"writer\">김이름</div>\r\n");
      out.write("													<div class=\"date\">2021.1.15</div>\r\n");
      out.write("													<div class=\"count\"><a href=\"board_edit.html\" class=\"button\">수정</a></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"num\">3</div>\r\n");
      out.write("													<div class=\"title\"><a href=\"view.html\">글 제목이 들어갑니다.</a></div>\r\n");
      out.write("													<div class=\"writer\">김이름</div>\r\n");
      out.write("													<div class=\"date\">2021.1.15</div>\r\n");
      out.write("													<div class=\"count\"><a href=\"board_edit.html\" class=\"button\">수정</a></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"num\">2</div>\r\n");
      out.write("													<div class=\"title\"><a href=\"view.html\">글 제목이 들어갑니다.</a></div>\r\n");
      out.write("													<div class=\"writer\">김이름</div>\r\n");
      out.write("													<div class=\"date\">2021.1.15</div>\r\n");
      out.write("													<div class=\"count\"><a href=\"board_edit.html\" class=\"button\">수정</a></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"num\">1</div>\r\n");
      out.write("													<div class=\"title\"><a href=\"view.html\">글 제목이 들어갑니다.</a></div>\r\n");
      out.write("													<div class=\"writer\">김이름</div>\r\n");
      out.write("													<div class=\"date\">2021.1.15</div>\r\n");
      out.write("													<div class=\"count\"><a href=\"board_edit.html\" class=\"button\">수정</a></div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<br><br><br>\r\n");
      out.write("											<div>\r\n");
      out.write("											<ul class=\"pagination\">\r\n");
      out.write("												<li><span class=\"button disabled\">이전</span></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page active\">1</a></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page\">2</a></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page\">3</a></li>\r\n");
      out.write("												<li><span>&hellip;</span></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page\">8</a></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page\">9</a></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"page\">10</a></li>\r\n");
      out.write("												<li><a href=\"#\" class=\"button\">다음</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("											</div>\r\n");
      out.write("											<ul class=\"pagination\">\r\n");
      out.write("											<a href=\"board_write.html\" ><input type=\"submit\" value=\"등록\" class=\"primary\" /></a>\r\n");
      out.write("											</ul>	\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Sidebar -->\r\n");
      out.write("					<div id=\"sidebar\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Search -->\r\n");
      out.write("								<section id=\"search\" class=\"alt\">\r\n");
      out.write("									<form method=\"post\" action=\"#\">\r\n");
      out.write("										<input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\r\n");
      out.write("									</form>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("								<nav id=\"menu\">\r\n");
      out.write("									\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("										<li><a href=\"mypage.jsp\">회원정보수정</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("\r\n");
      out.write("							<!-- Menu -->\r\n");
      out.write("								<nav id=\"menu\">\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>현장 관리 메뉴</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"fieldlist.jsp\">현장 목록 </a></li>\r\n");
      out.write("										<li><a href=\"board_list.jsp\">관리 일지</a></li>\r\n");
      out.write("                              			<li><a href=\"notice.jsp\">경고 발생 현황</a></li>\r\n");
      out.write("										<!-- <li><a href=\"elements.html\">SafeBox List Manage</a></li> -->\r\n");
      out.write("										<!-- <li><a href=\"safebox.html\">SafeBox List</a></li> -->\r\n");
      out.write("										<!-- <li>\r\n");
      out.write("											<span class=\"opener\">Submenu</span>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\">Lorem Dolor</a></li>\r\n");
      out.write("												<li><a href=\"#\">Ipsum Adipiscing</a></li>\r\n");
      out.write("												<li><a href=\"#\">Tempus Magna</a></li>\r\n");
      out.write("												<li><a href=\"#\">Feugiat Veroeros</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</li> -->\r\n");
      out.write("										\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<!-- <section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>Ante interdum</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<div class=\"mini-posts\">\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic07.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic08.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic09.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"actions\">\r\n");
      out.write("										<li><a href=\"#\" class=\"button\">More</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section> -->\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>내 정보</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									\r\n");
      out.write("									<ul class=\"contact\">\r\n");
      out.write("										<li class=\"icon solid fa-envelope\"><a href=\"#\">information@untitled.tld</a></li>\r\n");
      out.write("										<li class=\"icon solid fa-phone\">(000) 000-0000</li>\r\n");
      out.write("										<li class=\"icon solid fa-home\">1234 Somewhere Road #8254<br />\r\n");
      out.write("										Nashville, TN 00000-0000</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section>\r\n");
      out.write("\r\n");
      out.write("							<!-- Footer -->\r\n");
      out.write("								<footer id=\"footer\">\r\n");
      out.write("									<p class=\"copyright\">&copy; Untitled. All rights reserved. Demo Images: <a href=\"https://unsplash.com\">Unsplash</a>. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("								</footer>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("			<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
