/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-17 00:42:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sensorValue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("   Editorial by HTML5 UP\r\n");
      out.write("   html5up.net | @ajlkn\r\n");
      out.write("   Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>Edito UP</title>\r\n");
      out.write("      <meta charset=\"utf-8\" />\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("	  <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js\"></script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <style>\r\n");
      out.write("	   .section{\r\n");
      out.write("			position: relative;\r\n");
      out.write("	   }\r\n");
      out.write("	   .article {\r\n");
      out.write("		   position: relative;\r\n");
      out.write("	   }\r\n");
      out.write("	   .posts{\r\n");
      out.write("			position: relative;\r\n");
      out.write("	   }\r\n");
      out.write("      table .ttbody{\r\n");
      out.write("         position: relative;\r\n");
      out.write("         vertical-align: middle;\r\n");
      out.write("      }\r\n");
      out.write("      .switch-button { position: relative; display: inline-block; width: 55px; height: 30px; } \r\n");
      out.write("      .switch-button input { opacity: 0; width: 0; height: 0; } \r\n");
      out.write("      .switch-button input:checked + .onoff-switch { background-color: #F2D522; box-shadow: inset 1px 5px 1px #E3AE56; } \r\n");
      out.write("      .switch-button input:checked + .onoff-switch:before { -webkit-transform: translateX(26px); -ms-transform: translateX(26px); transform: translateX(26px); }\r\n");
      out.write("      .onoff-switch { position: absolute; cursor: pointer; top: 0; left: 0; right: 0; bottom: 0; border-radius:20px; background-color: #ccc; box-shadow: inset 1px 5px 1px #999; -webkit-transition: .4s; transition: .4s; } \r\n");
      out.write("      .onoff-switch:before { position: absolute; content: \"\"; height: 22px; width: 22px; left: 4px; bottom: 4px; background-color: #fff; -webkit-transition: .5s; transition: .4s; border-radius:20px; }\r\n");
      out.write("      .onoff-switch {\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			} \r\n");
      out.write("   </style>\r\n");
      out.write("   \r\n");
      out.write("   <body class=\"is-preload\">	\r\n");
      out.write("      <!-- Wrapper -->\r\n");
      out.write("         <div id=\"wrapper\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Main -->\r\n");
      out.write("               <div id=\"main\">\r\n");
      out.write("                  <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("                     <!-- Header -->\r\n");
      out.write("                        <header id=\"header\">\r\n");
      out.write("                           <a href=\"sensorValue.jsp\" class=\"logo\" style=\"font-size: 20px;\"><strong>현장명</strong>  <br> 현장 주소</a>\r\n");
      out.write("                           \r\n");
      out.write("                           <ul class=\"icons\">\r\n");
      out.write("                              \r\n");
      out.write("                              <li><a href=\"notice.jsp\" class=\"logo\"><span class=\"label\"><strong>경고발생현황</strong></span></a></li>\r\n");
      out.write("                              <li><a href=\"board_list.jsp\".html\" class=\"logo\"><span class=\"label\">관리일지</span></a></li>\r\n");
      out.write("                               \r\n");
      out.write("                              \r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </header>                                  \r\n");
      out.write("                                    \r\n");
      out.write("                     	<!-- Section -->\r\n");
      out.write("								<section class=\"section\">\r\n");
      out.write("									<!-- <header class=\"major\">\r\n");
      out.write("										<h2>관리 현장 목록</h2>\r\n");
      out.write("									</header> -->\r\n");
      out.write("									<div class=\"posts\">\r\n");
      out.write("										<article class=\"article\">\r\n");
      out.write("											\r\n");
      out.write("											<h3>SAFEBOX ID</h3>\r\n");
      out.write("											<p>기기 위치</p>\r\n");
      out.write("													<div class=\"table-wrapper\">\r\n");
      out.write("														<table>\r\n");
      out.write("															<thead>\r\n");
      out.write("																<tr>\r\n");
      out.write("                                                   <th>센서 ID</th>\r\n");
      out.write("                                                   <th>ON/OFF</th>\r\n");
      out.write("                                                   <th>기기상태</th>\r\n");
      out.write("                                                   <th>진동세기</th>\r\n");
      out.write("                                                   <th>현재세기</th>\r\n");
      out.write("                                                   <th>측정주기</th>\r\n");
      out.write("                                                   <th>설정변경</th>\r\n");
      out.write("																</tr>\r\n");
      out.write("															</thead>\r\n");
      out.write("															<tbody  class=\"ttbody\">\r\n");
      out.write("																<tr>\r\n");
      out.write("																	<td >Item1</td>\r\n");
      out.write("                                                   <td style=\"vertical-align:bottom;\"><label class=\"switch-button\"><input type=\"checkbox\"/> <div class=\"onoff-switch\"></div> </label></td>\r\n");
      out.write("                                                   <td style=\"vertical-align:middle;\"><img src=\"images/정상동그라미.png\" ></td>\r\n");
      out.write("                                                   <td></td>\r\n");
      out.write("                                                   <td></td>\r\n");
      out.write("																	<td></td>\r\n");
      out.write("																	<td><form action=\"sensorManage.jsp\"><input type=\"submit\" value=\"설정\"></form></td>											\r\n");
      out.write("																</tr>\r\n");
      out.write("                                                <table>\r\n");
      out.write("                                                   <thead>\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                         <th>센서 ID</th>\r\n");
      out.write("                                                         <th>ON/OFF</th>\r\n");
      out.write("                                                         <th>기기상태</th>\r\n");
      out.write("                                                         <th>기준농도</th>\r\n");
      out.write("                                                         <th>현재농도</th>\r\n");
      out.write("                                                         <th>측정주기</th>\r\n");
      out.write("                                                         <th>설정변경</th>\r\n");
      out.write("      \r\n");
      out.write("                                                      </tr>\r\n");
      out.write("                                                   </thead>\r\n");
      out.write("                                                   <tbody  class=\"ttbody\">\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                         <td >Item1</td>\r\n");
      out.write("                                                         <td style=\"vertical-align:bottom;\"><label class=\"switch-button\"><input type=\"checkbox\"/> <div class=\"onoff-switch\"></div> </label></td>\r\n");
      out.write("                                                         <td style=\"vertical-align:middle;\"><img src=\"images/비정상동그라미.png\" ></td>\r\n");
      out.write("                                                         <td></td>\r\n");
      out.write("                                                         <td></td>\r\n");
      out.write("                                                         <td></td>\r\n");
      out.write("                                                         <td><form action=\"sensorManage.jsp\"><input type=\"submit\" value=\"설정\"></form></td>											\r\n");
      out.write("                                                      </tr>\r\n");
      out.write("																\r\n");
      out.write("																\r\n");
      out.write("																\r\n");
      out.write("															</tbody>\r\n");
      out.write("															\r\n");
      out.write("														</table>\r\n");
      out.write("													</div>\r\n");
      out.write("											\r\n");
      out.write("										</article>\r\n");
      out.write("                             \r\n");
      out.write("													\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("               </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("               <div id=\"sidebar\">\r\n");
      out.write("                  <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("                     <!-- Search -->\r\n");
      out.write("                        <section id=\"search\" class=\"alt\">\r\n");
      out.write("                           <form method=\"post\" action=\"#\">\r\n");
      out.write("                              <input type=\"text\" name=\"query\" id=\"query\" placeholder=\"Search\" />\r\n");
      out.write("                           </form>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                        <nav id=\"menu\">\r\n");
      out.write("									\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("										<li><a href=\"mypage.jsp\">회원정보수정</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("\r\n");
      out.write("							<!-- Menu -->\r\n");
      out.write("								<nav id=\"menu\">\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>현장 관리 메뉴</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"fieldlist.jsp\">현장 목록 </a></li>\r\n");
      out.write("										<li><a href=\"sensorList.jsp\">센서 목록 </a></li>\r\n");
      out.write("										<li><a href=\"board_list.jsp\">관리 일지</a></li>\r\n");
      out.write("                              			<li><a href=\"notice.jsp\">경고 발생 현황</a></li>\r\n");
      out.write("										\r\n");
      out.write("										\r\n");
      out.write("									</ul>\r\n");
      out.write("								</nav>\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<!-- <section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>Ante interdum</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("									<div class=\"mini-posts\">\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic07.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic08.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("										<article>\r\n");
      out.write("											<a href=\"#\" class=\"image\"><img src=\"images/pic09.jpg\" alt=\"\" /></a>\r\n");
      out.write("											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>\r\n");
      out.write("										</article>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"actions\">\r\n");
      out.write("										<li><a href=\"#\" class=\"button\">More</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</section> -->\r\n");
      out.write("\r\n");
      out.write("							<!-- Section -->\r\n");
      out.write("								<section>\r\n");
      out.write("									<header class=\"major\">\r\n");
      out.write("										<h2>내 정보</h2>\r\n");
      out.write("									</header>\r\n");
      out.write("                           \r\n");
      out.write("                           <ul class=\"contact\">\r\n");
      out.write("                              <li class=\"icon solid fa-envelope\"><a href=\"#\">information@untitled.tld</a></li>\r\n");
      out.write("                              <li class=\"icon solid fa-phone\">(000) 000-0000</li>\r\n");
      out.write("                              <li class=\"icon solid fa-home\">1234 Somewhere Road #8254<br />\r\n");
      out.write("                              Nashville, TN 00000-0000</li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </section>\r\n");
      out.write("\r\n");
      out.write("                     <!-- Footer -->\r\n");
      out.write("                        <footer id=\"footer\">\r\n");
      out.write("                           <p class=\"copyright\">&copy; Untitled. All rights reserved. Demo Images: <a href=\"https://unsplash.com\">Unsplash</a>. Design: <a href=\"https://html5up.net\">HTML5 UP</a>.</p>\r\n");
      out.write("                        </footer>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Scripts -->\r\n");
      out.write("         <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("         <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
